### ISSUE TITLE
ImportError: No module named gnuradio

### ISSUE THREAD

**Issue by wright3189** [ptrkrysik/gr-gsm#151]
I'm on Fedora Linux 4.3.5-300.fc23.x86_64. I was able to install gr-gsm via PyBOMBS, however, when I run it:

[root@new-host awright]# grgsm_decode
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_decode", line 24, in <module>
    from gnuradio import blocks
ImportError: No module named gnuradio
[root@new-host awright]# grgsm_livemon
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_livemon", line 19, in <module>
    from gnuradio import blocks
ImportError: No module named gnuradio
[root@new-host awright]# grgsm_scanner
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_scanner", line 24, in <module>
    from gnuradio import blocks
ImportError: No module named gnuradio

When I install gnuradio via the Fedora repo I get:

[root@new-host awright]# grgsm_decode
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_decode", line 30, in <module>
    import grgsm
ImportError: No module named grgsm
[root@new-host awright]# grgsm_livemon
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_livemon", line 28, in <module>
    import grgsm
ImportError: No module named grgsm
[root@new-host awright]# grgsm_scanner
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_scanner", line 33, in <module>
    import grgsm
ImportError: No module named grgsm

Seems like it can't find any of the modules. Any solution to this?

**Comment by wright3189** [comment]
This is what fixed it for me (thanks phocean):

% cat /etc/ld.so.conf.d/gr-gsm.conf 
/usr/local/lib64
**/usr/local/lib**
% sudo ldconfig

Adding the following line in my $HOME/.bashrc:
PYTHONPATH=$PYTHONPATH:/usr/local/lib64/python2.7/site-packages/
export PYTHONPATH
