### ISSUE TITLE
ImportError: libgnuradio-runtime

### ISSUE THREAD

**Issue by nbalkanas** [ptrkrysik/gr-gsm#190]
Hi,

I'm getting the following error when trying to run grgsm_livemon:

-> grgsm_livemon -h
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_livemon", line 29, in <module>
    import osmosdr
  File "/usr/local/lib/python2.7/dist-packages/osmosdr/__init__.py", line 26, in <module>
    from osmosdr_swig import *
  File "/usr/local/lib/python2.7/dist-packages/osmosdr/osmosdr_swig.py", line 28, in <module>
    _osmosdr_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/osmosdr/osmosdr_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_osmosdr_swig', fp, pathname, description)
ImportError: libgnuradio-runtime-3.7.6.1.so.0.0.0: cannot open shared object file: No such file or directory

I have followed ticket #163. Reinstalled latest gnuradio, bladeRF, osmosdr, airspy and grgsm from git sources. Compiled and installed fine. sudo ldconfig after each step. I even rm -rf /usr/local/lib/python2.7/dist-packages/osmosdr, and ran it without the swig directory, I still get the same error! I used to have libgnuradio-runtime-3.7.6.1 ages ago, but have since upgraded to libgnuradio-runtime-3.7.9.2 (the latest). libgnuradio-runtime-3.7.6.1 must be hardwired smw, I can't figure out where.

Any help is appreciated
Nikos

**Comment by nbalkanas** [comment]
This actually is a gr-osmosdr issue, not a gr-gsm...
