### ISSUE TITLE
can not run   airprobe_rtlsdr.py

### ISSUE THREAD

**Issue by Mahmoudshakra** [ptrkrysik/gr-gsm#229]
i have installed gr-gsm by Compiling and installing   Pybombs
and when i am try to run airprobe_rtlsdr.py it gives me this msg : 

Traceback (most recent call last):
  File "/usr/local/bin/airprobe_rtlsdr.py", line 28, in <module>
    from gnuradio.qtgui import Range, RangeWidget
ImportError: cannot import name Range

**Comment by Mahmoudshakra** [comment]
when i tried to run gnuradio-companion it gives me : 

Traceback (most recent call last):
  File "/usr/local/bin/gnuradio-companion", line 99, in <module>
    run_main()
  File "/usr/local/bin/gnuradio-companion", line 87, in run_main
    from gnuradio.grc.main import main
ImportError: No module named main

**Comment by ptrkrysik** [comment]
Probably you have problem with your gnuradio installation. If you intend to continue this thread please go to the gr-gsm's mailing list.
