### ISSUE TITLE
ImportError: No module named _qtgui_swig

### ISSUE THREAD

**Issue by PieBru** [ptrkrysik/gr-gsm#231]
Hi, after no reply on the mailing list I'm landing here, sorry for the duplicate.
I tryed to install gr-gsm in a clean, minimal and updated Arch Linux VM, the desktop is Lxde.
I get the same ImportError by installing gr-gsm-git via pacman PKGBUILD or manually from a cloned git repo, and even on a phisical PC with Arch + Gnome 3.22 .

```
[user1@archvm1]$ sudo pacman -S python2-pyqt4 doxygen
[user1@archvm1]$ git clone https://github.com/ptrkrysik/gr-gsm && cd gr-gsm
[user1@archvm1]$ mkdir build && cd build && cmake .. && make && sudo make install
[user1@archvm1 build]$ grgsm_livemon -h
Traceback (most recent call last):
  File "/usr/bin/grgsm_livemon", line 25, in <module>
    from gnuradio import qtgui
  File "/usr/lib/python2.7/site-packages/gnuradio/qtgui/__init__.py", line 35, in <module>
    from qtgui_swig import *
  File "/usr/lib/python2.7/site-packages/gnuradio/qtgui/qtgui_swig.py", line 21, in <module>
    _qtgui_swig = swig_import_helper()
  File "/usr/lib/python2.7/site-packages/gnuradio/qtgui/qtgui_swig.py", line 20, in swig_import_helper
    return importlib.import_module('_qtgui_swig')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named _qtgui_swig

```
Any hint?
Thanks,
Piero

**Comment by PieBru** [comment]
Well, this was quickly solved thanks to an Arch guru.

It was as simple as manually installing gnuradio-companion which isn't between gr-gsm-git dependencies.
I was fooled because gnuradio already installed /usr/lib/python2.7/site-packages/gnuradio/qtgui/qtgui_swig.*

Piero
