### ISSUE TITLE
Error running grgsm_decode

### ISSUE THREAD

**Issue by 78bash** [ptrkrysik/gr-gsm#239]
Help!

I'm testing grgsm_decode as per the instructions on the How To wiki at:
https://github.com/ptrkrysik/gr-gsm/wiki/Usage:-Decoding-How-To

I reach the final step to run:
grgsm_decode -c vf_call6_a725_d174_g5_Kc1EF00BAB3BAC7002.cfile -s $((100000000/174)) -a 725 -m TCHF -t 5 -e 1 -k 0x1E,0xF0,0x0B,0xAB,0x3B,0xAC,0x70,0x02 -d FR -o /tmp/speech.au.gsm

I receive:

Traceback (most recent call last):
  File "/usr/local/bin/grgsm_decode", line 387, in <module>
    print_bursts=options.print_bursts, ppm=options.ppm)
  File "/usr/local/bin/grgsm_decode", line 100, in __init__
    self.tch_f_decoder = grgsm.tch_f_decoder(speech_codec, enable_voice_boundary_detection)
  File "/usr/local/lib/python2.7/dist-packages/grgsm/grgsm_swig.py", line 1826, in make
    return _grgsm_swig.tch_f_decoder_make(mode, boundary_check)
TypeError: in method 'tch_f_decoder_make', argument 2 of type 'bool'

What should I do?
Thanks

**Comment by 78bash** [comment]
Sorry, I just noticed issue #206 is the same issue.
