### ISSUE TITLE
Not able to do a livemon

### ISSUE THREAD

**Issue by jorgemqr** [ptrkrysik/gr-gsm#463]
hello newbie here: 

while trying to execute command:

root@kali:~/Descargas/gr-gsm-0.41.2# grgsm_livemon
Traceback (most recent call last):
  File "/usr/bin/grgsm_livemon", line 45, in <module>
    from gnuradio import qtgui
  File "/usr/lib/python2.7/dist-packages/gnuradio/qtgui/__init__.py", line 37, in <module>
    from range import Range, RangeWidget
  File "/usr/lib/python2.7/dist-packages/gnuradio/qtgui/range.py", line 67, in <module>
    class RangeWidget(QtWidgets.QWidget):
AttributeError: 'module' object has no attribute 'QWidget'

is there any fix ? thank you in advance.

**Comment by jorgemqr** [comment]
i was able to fix it by doing the installation process from https://osmocom.org/projects/gr-gsm/wiki/Installation just followed the instrucctions of section Manual compilation and installation, i first installed it with PyBombs (not neccesary to delete the PyBombs work cause it is running), also just for your information i am using a Kali GNU/Linux Rolling \n \l
