### ISSUE TITLE
cmake .. Error

### ISSUE THREAD

**Issue by greencorsairs** [ptrkrysik/gr-gsm#502]
![Sans titre](https://user-images.githubusercontent.com/60856553/74109228-fa465880-4b81-11ea-9fba-5e7c1b69e9d8.png)

**Comment by velichkov** [comment]
Hi @greencorsairs,

See #480 and #475. And in the future please do not attach screenshots of your terminal, you can copy-paste the text instead.

**Comment by greencorsairs** [comment]
[ 73%] Generating grgsm_livemon
<<< Welcome to GNU Radio Companion Compiler 3.8.0.0 >>>

Block paths:
/root/.grc_gnuradio
/home/leone/Desktop/gr-gsm/grc
/usr/share/gnuradio/grc/blocks

>>> Loading: /home/leone/Desktop/gr-gsm/apps/grgsm_livemon.grc
Exception in static block register_rfnoc_block_ctrl
RuntimeError: Attempting to register an RFNoC block with key Block for the second time.
Exception in static block register_rfnoc_ddc_block_ctrl
RuntimeError: Attempting to register an RFNoC block with key DDC for the second time.
Exception in static block register_rfnoc_duc_block_ctrl
RuntimeError: Attempting to register an RFNoC block with key DUC for the second time.
Exception in static block register_rfnoc_fir_block_ctrl
RuntimeError: Attempting to register an RFNoC block with key FIR for the second time.
Exception in static block register_rfnoc_null_block_ctrl
RuntimeError: Attempting to register an RFNoC block with key NullSrcSink for the second time.
Exception in static block register_rfnoc_window_block_ctrl
RuntimeError: Attempting to register an RFNoC block with key Window for the second time.
Exception in static block register_rfnoc_siggen_block_ctrl
RuntimeError: Attempting to register an RFNoC block with key SigGen for the second time.
Exception in static block register_rfnoc_dma_fifo_block_ctrl
RuntimeError: Attempting to register an RFNoC block with key DmaFIFO for the second time.
Exception in static block register_rfnoc_replay_block_ctrl
RuntimeError: Attempting to register an RFNoC block with key Replay for the second time.
Exception in static block reg_basic_and_lf_dboards
LookupError: KeyError: The dboard id 0x0000 is already registered to Basic TX.
Exception in static block reg_rfx_dboards
LookupError: KeyError: The dboard id pair [0x0024, 0x0028] is already registered to RFX400.
Exception in static block reg_xcvr2450_dboard
LookupError: KeyError: The dboard id pair [0x0061, 0x0060] is already registered to XCVR2450.
Exception in static block reg_sbx_dboards
LookupError: KeyError: The dboard id pair [0x0054, 0x0055] is already registered to SBX.
Exception in static block reg_ubx_dboards
LookupError: KeyError: The dboard id pair [0x0074, 0x0073] is already registered to UBX v0.3.
Exception in static block reg_wbx_simple_dboards
LookupError: KeyError: The dboard id pair [0x0053, 0x0052] is already registered to WBX.
Exception in static block reg_dbsrx_dboard
LookupError: KeyError: The dboard id 0x000d is already registered to DBSRX.
Exception in static block reg_unknown_dboards
LookupError: KeyError: The dboard id 0xfff0 is already registered to Unknown TX.
Exception in static block reg_tvrx_dboard
LookupError: KeyError: The dboard id 0x0040 is already registered to TVRX.
Exception in static block reg_dbsrx2_dboard
LookupError: KeyError: The dboard id 0x0012 is already registered to DBSRX2.
Exception in static block reg_tvrx2_dboard
LookupError: KeyError: The dboard id 0x0046 is already registered to TVRX2.
Exception in static block reg_twinrx_dboards
LookupError: KeyError: The dboard id 0x0091 is already registered to TwinRX Rev A.
Exception in static block register_rfnoc_e320_radio_ctrl
RuntimeError: Attempting to register an RFNoC block with key NeonRadio for the second time.
Exception in static block register_rfnoc_magnesium_radio_ctrl
RuntimeError: Attempting to register an RFNoC block with key MagnesiumRadio for the second time.
Exception in static block register_rfnoc_rhodium_radio_ctrl
RuntimeError: Attempting to register an RFNoC block with key RhodiumRadio for the second time.
Exception in static block register_rfnoc_x300_radio_ctrl
RuntimeError: Attempting to register an RFNoC block with key X300Radio for the second time.
>>> Generating: /home/leone/Desktop/gr-gsm/build/apps/grgsm_livemon.py
double free or corruption (!prev)
Child aborted
make[2]: *** [apps/CMakeFiles/pygen_apps.dir/build.make:85: apps/grgsm_livemon] Error 1
make[1]: *** [CMakeFiles/Makefile2:590: apps/CMakeFiles/pygen_apps.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

**Comment by velichkov** [comment]
Try to disable building of `grgsm_livemon` and `grgsm_livemon_headless`  
```
cmake -DENABLE_GRCC=OFF ..
```
and then if it builds and installs successfully try building `apps/grgsm_livemon.grc` and `apps/grgsm_livemon_headless.grc` manually using `gnuradio-companion`.

```
gnuradio-companion apps/grgsm_livemon.grc
gnuradio-companion apps/grgsm_livemon_headless.grc
```

**Comment by greencorsairs** [comment]
#grgsm_livemon
Traceback (most recent call last):
File "/usr/bin/grgsm_livemon", line 25, in <module>
from gnuradio import blocks
ImportError: No module named gnuradio

**Comment by velichkov** [comment]
https://github.com/ptrkrysik/gr-gsm/search?q=%22ImportError%3A+No+module+named+gnuradio%22&type=Issues

https://github.com/ptrkrysik/gr-gsm/issues/480#issuecomment-532305188

**Comment by greencorsairs** [comment]
do you have a tutorial i can follow ?

**Comment by velichkov** [comment]
> do you have a tutorial i can follow ?

Sorry, I don't have. The [official instructions](https://osmocom.org/projects/gr-gsm/wiki/Installation#Debbian-based-distributions-Debian-Testing-Ubuntu-1604-Kali-Rolling-Edition) are probably a bit outdated in regards to gnuradio 3.8 but they are still useful. Avoid the `pybombs` installation method as in my opinion it is the hardest and most error prone one.  Also read all messages in #480. 

When asking for help it's usually good to provide some more details about your system and what you did, like which Linux distribution do you use, how did you install gnuradio, gr-osmosdr and gr-gsm and which versions, which commands did you execute including all their arguments and their outout, etc... 

You may also post to our [mailing list](https://github.com/ptrkrysik/gr-gsm/#mailing-list).

**Comment by greencorsairs** [comment]
how i can get tmsi and key ?

**Comment by greencorsairs** [comment]
how i can get tmsi and key of the phone number ?

**Comment by 9600** [comment]
By being the mobile operator or other entity provisioning the SIM card and key etc.

**Comment by greencorsairs** [comment]
how i can find that ?

**Comment by greencorsairs** [comment]
![image](https://user-images.githubusercontent.com/60856553/75609826-003db280-5b0c-11ea-8945-eadc193ffb07.png)

**Comment by 9600** [comment]
Simple, just set up your own mobile phone company.

**Comment by greencorsairs** [comment]
how ?

**Comment by greencorsairs** [comment]
I have a phone number how can I get TMSI and KC !

**Comment by greencorsairs** [comment]
do you have a tutorial i can follow ?

**Comment by greencorsairs** [comment]
thanks

**Comment by greencorsairs** [comment]
#grgsm_livemon
Traceback (most recent call last):
File "/usr/bin/grgsm_livemon", line 25, in
from gnuradio import blocks
ImportError: No module named gnuradio

**Comment by greencorsairs** [comment]
!!
