### ISSUE TITLE
grgsm_livemon

### ISSUE THREAD

**Issue by artem222414** [ptrkrysik/gr-gsm#557]
grgsm_livemon
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/grgsm/__init__.py", line 48, in <module>
    from .grgsm_swig import *
  File "/usr/lib/python3.8/site-packages/grgsm/grgsm_swig.py", line 13, in <module>
    from . import _grgsm_swig
ImportError: libgnuradio-filter.so.3.8.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/sbin/grgsm_livemon", line 37, in <module>
    from grgsm import arfcn
  File "/usr/lib/python3.8/site-packages/grgsm/__init__.py", line 48, in <module>
    from .grgsm_swig import *
  File "/usr/lib/python3.8/site-packages/grgsm/grgsm_swig.py", line 13, in <module>
    from . import _grgsm_swig
ImportError: libgnuradio-filter.so.3.8.0: cannot open shared object file: No such file or directory
pls help me

**Comment by velichkov** [comment]
Hi @artem222414,

> ImportError: libgnuradio-filter.so.3.8.0: cannot open shared object file: No such file or directory

My advice is to reinstall gr-gsm.
