### ISSUE TITLE
AttributeError: module 'osmosdr' has no attribute 'source

### ISSUE THREAD

**Issue by Fcukcpp** [ptrkrysik/gr-gsm#588]
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_livemon", line 385, in <module>
    main()
  File "/usr/local/bin/grgsm_livemon", line 361, in main
    tb = top_block_cls(args=options.args, collector=options.collector, collectorport=options.collectorport, fc=options.fc, gain=options.gain, osr=options.osr, ppm=options.ppm, samp_rate=options.samp_rate, serverport=options.serverport, shiftoff=options.shiftoff)
  File "/usr/local/bin/grgsm_livemon", line 112, in __init__
    self.rtlsdr_source_0 = osmosdr.source(
AttributeError: module 'osmosdr' has no attribute 'source

**Comment by velichkov** [comment]
Hi @Fcukcpp,

Which Linux distribution do you use and which version? How did you install gnuradio, gr-osmosdr and gr-gsm and which versions?

> AttributeError: module 'osmosdr' has no attribute 'source

Most probably there is an undefined symbol in `libgnuradio-osmosdr.so` file. You need to locate this file and execute `ldd -r libgnuradio-osmosdr.so` (in your terminal in the same directory where this file is located) and provide the full output.
