### ISSUE TITLE
grgsm_livemon giving issue 

### ISSUE THREAD

**Issue by Lihsrah** [ptrkrysik/gr-gsm#613]
5.18.0-kali5-amd64

i am new to gr-gsm , sorry if i come out dumb :')

**ERROR**

> └─$ sudo grgsm_livemon                                                        
/usr/bin/grgsm_livemon:13: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import StrictVersion
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/grgsm/__init__.py", line 48, in <module>
    from .grgsm_swig import *
  File "/usr/lib/python3/dist-packages/grgsm/grgsm_swig.py", line 13, in <module>
    from . import _grgsm_swig
ImportError: cannot import name '_grgsm_swig' from partially initialized module 'grgsm' (most likely due to a circular import) (/usr/lib/python3/dist-packages/grgsm/__init__.py)
Traceback (most recent call last):
  File "/usr/bin/grgsm_livemon", line 37, in <module>
    from grgsm import arfcn
  File "/usr/lib/python3/dist-packages/grgsm/__init__.py", line 48, in <module>
    from .grgsm_swig import *
  File "/usr/lib/python3/dist-packages/grgsm/grgsm_swig.py", line 13, in <module>
    from . import _grgsm_swig
ImportError: cannot import name '_grgsm_swig' from partially initialized module 'grgsm' (most likely due to a circular import) (/usr/lib/python3/dist-packages/grgsm/__init__.py)

![image](https://user-images.githubusercontent.com/73928189/184031142-3db8838e-880a-427a-b714-fb5cd1756820.png)

**Comment by velichkov** [comment]
How did you install gnuradio and gr-gsm and which versions?

**Comment by Lihsrah** [comment]
from official kali rolling repo

> └─$ sudo apt install gnuradio
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
gnuradio is already the newest version (3.10.3.0-2+b1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


and gr-gsm from this repo :-
https://github.com/bkerler/gr-gsm


in your repo i was getting this error: 

![image](https://user-images.githubusercontent.com/73928189/184494631-18210085-27c8-439c-954e-894245668e85.png)

**Comment by velichkov** [comment]
> and gr-gsm from this repo :-
> https://github.com/bkerler/gr-gsm

Then you most probably have some leftovers from a previous installation

> File "/usr/lib/python3/dist-packages/grgsm/grgsm_swig.py", line 13, in
> from . import _grgsm_swig

The version for gnuradio 3.10 no longer uses `swig` so the above file is from a previous installation that you need to remove. First remove all gr-gsm's files from `/usr/` and `/usr/local and then reinstall.

**Comment by Lihsrah** [comment]
`cmake ..`   in your repo give me this 

![image](https://user-images.githubusercontent.com/73928189/184677718-4037eb68-2748-449c-8f32-724708e2d159.png)

**Comment by velichkov** [comment]
> cmake .. in your repo give me this

Yes, because the `main` branch in my repo contains the version for `gnuradio 3.8`. As you have `gnuradio 3.10` you need to get the version/branch for `gnuradio 3.10`. 

Use `maint-3.10` or `maint-3.10_with_multiarfcn` branches from [bkerler's fork](https://github.com/bkerler/gr-gsm) but before installing it make sure that there are no gr-gsm's files from a previous installation in `/usr/` and `/usr/local/`.

**Comment by Mhagne** [comment]
![image](https://user-images.githubusercontent.com/106419285/186562620-d4e2db73-6987-4122-9ada-fc0a2233fd53.jpeg)

**Comment by Mhagne** [comment]
in your repo give me this please help me

**Comment by velichkov** [comment]
Why are you building `gr-osmosdr` from source? Why don't you install it using the package manager of your Linux distribution?

> in your repo give me this please help me

You need to install `libsndfile`. For Ubuntu/Debian/Kali run `sudo apt-get instlal libsndfile-dev`

P.S.
Do not attach screenshots of your terminal. It is much better to copy-paste the test.

**Comment by Mhagne** [comment]
Sometimes it appears to me

make: *** no targets specified and no makefile found , stop

**Comment by velichkov** [comment]
> make: *** no targets specified and no makefile found , stop

You either are executing `make` in a different directory then `cmake` or you have not run `cmake` before `make`

**Comment by Mhagne** [comment]
CMake Error at swig/CMakeLists.txt:37 (include):
  include could not find requested file:                                                            
                                                                                                    
    GrSwig                                                                                          
                                                                                                    
                                                                                                    
CMake Error at swig/CMakeLists.txt:51 (GR_SWIG_MAKE):
  Unknown CMake command "GR_SWIG_MAKE".

**Comment by Mhagne** [comment]
‏When I open {{cmake ..}}this problem appears to me
‏I deleted it more than once with the same problem, please help me

‏Error
CMake Error at swig/CMakeLists.txt:37 
(include): include could not find requested file:
GrSwig                                                                                          
CMake Error at swig/CMakeLists.txt:51 (GR_SWIG_MAKE): Unknown CMake command "GR_SWIG_MAKE".

**Comment by WilfredoLora** [comment]
> > cmake .. in your repo give me this
> 
> Yes, because the `main` branch in my repo contains the version for `gnuradio 3.8`. As you have `gnuradio 3.10` you need to get the version/branch for `gnuradio 3.10`.
> 
> Use `maint-3.10` or `maint-3.10_with_multiarfcn` branches from [bkerler's fork](https://github.com/bkerler/gr-gsm) but before installing it make sure that there are no gr-gsm's files from a previous installation in `/usr/` and `/usr/local/`.

Thanks for sharing the bkerler/gr-gsm fork for GR3.10. It compiled with no issue!!!!
