### ISSUE TITLE
module 'gnuradio.blocks' has no attribute 'byte_t' on GNU Radio 3.10

### ISSUE THREAD

**Issue by alphafox02** [ptrkrysik/gr-gsm#617]
While following this guide https://github.com/ptrkrysik/gr-gsm/wiki/Usage:-Decoding-How-To using the file provided on a 22.04 Jammy / GNU Radio 3.10.4 / https://github.com/ptrkrysik/gr-gsm/pull/600 installation I see the following after running this command,

```
grgsm_decode -c vf_call6_a725_d174_g5_Kc1EF00BAB3BAC7002.cfile -s $((100000000/174)) -a 725 -m TCHF -t 5 -e 1 -k 0x1E,0xF0,0x0B,0xAB,0x3B,0xAC,0x70,0x02 -d FR -o /tmp/speech.au.gsm
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_decode", line 389, in <module>
    tb = gsm_decoder(timeslot=options.timeslot, subslot=options.subslot, chan_mode=options.chan_mode,
  File "/usr/local/bin/grgsm_decode", line 105, in __init__
    self.tch_f_pdu_to_tagged_stream = pdu.pdu_to_tagged_stream(blocks.byte_t, "packet_len")
AttributeError: module 'gnuradio.blocks' has no attribute 'byte_t'
```
Slight changes to the command line arguments can generate other issues (maybe expected)

```
grgsm_decode -c vf_call6_a725_d174_g5_Kc1EF00BAB3BAC7002.cfile -s $((100000000/174)) -a 725 -t 5 -e 1 -k 0x1E,0xF0,0x0B,0xAB,0x3B,0xAC,0x70,0x02 -d FR -o /tmp/speech.au.gsm
Traceback (most recent call last):
  File "/usr/local/bin/grgsm_decode", line 389, in <module>
    tb = gsm_decoder(timeslot=options.timeslot, subslot=options.subslot, chan_mode=options.chan_mode,
  File "/usr/local/bin/grgsm_decode", line 121, in __init__
    self.socket_pdu_server = pdu.socket_pdu("UDP_SERVER", "127.0.0.1", "4729", 10000) #added in order to avoid generating ICMP messages
AttributeError: module 'gnuradio.pdu' has no attribute 'socket_pdu'
```

I noticed what appeared to be the same issue here, but marked as resolved at some point. Unclear if they just made the tests work regardless of the failure or actually fixed the problem.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1003989

**Comment by alphafox02** [comment]
Comparing a dir(blocks) while in python3 command line on a 3.8 GNU Radio and GRGSM installation shows the byte_t attribute, along with burst_tagger_mark and burst_tagger_sptr. All three and more are missing on missing when performing the same dir(blocks) on a 3.10.4 GNU Radio and GRGSM installation.

**Comment by alphafox02** [comment]
Fixed by latest commit to https://github.com/ptrkrysik/gr-gsm/pull/600
