### ISSUE TITLE
grgsm_scanner and others not working with HackRF

### ISSUE THREAD

**Issue by OliverB21** [ptrkrysik/gr-gsm#636]
Hi all,

I have a HackRF One and am attempting to run the gr-gsm suite to analyse GSM traffic, however none of the tools seem to be working. These are the issues I am having, I assume they are related:

grgsm_livemon - Can see the frequency graph, although tuning into any frequency identified by kal doesn't provide any information.
grgsm_capture - Crashed out immediately, same error as below.
grgsm_scanner - Crashes out at 0%. Using --debug gives this error:

`Traceback (most recent call last):
  File "/usr/bin/grgsm_scanner", line 797, in <module>
    main()
  File "/usr/bin/grgsm_scanner", line 792, in main
    do_scan(options.samp_rate, options.band, options.speed,
  File "/usr/bin/grgsm_scanner", line 590, in do_scan
    scanner = wideband_scanner(rec_len=30 - speed,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/grgsm_scanner", line 444, in __init__
    str(gsm.device.get_default_args(args)))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gnuradio/gsm/device.py", line 53, in get_default_args
    devices = get_all_args("nofake")
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gnuradio/gsm/device.py", line 43, in get_all_args
    return list(map(lambda dev: dev.to_string(), exclude(get_devices(hint))))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gnuradio/gsm/device.py", line 40, in exclude
    return [dev for dev in devices if not match(dev, filters)]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gnuradio/gsm/device.py", line 40, in <listcomp>
    return [dev for dev in devices if not match(dev, filters)]
                                          ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/gnuradio/gsm/device.py", line 33, in match
    if (k not in dev or dev[k] != v):
        ^^^^^^^^^^^^

TypeError: argument of type 'osmosdr.osmosdr_python.device_t' is not iterable
`
All programs and firmware are up to date, kernel version is 6.5.0-kali3-amd64

TIA, and apologies for formatting

**Comment by OliverB21** [comment]
Update - Have tested with a Nooelec SDR with the same error on both programs, still unsure what is causing this particular issue...

**Comment by Bombik007** [comment]
same here...

**Comment by AnilSarode** [comment]
`sudo apt install hackrf`

You have to pass the args value 

`sudo grgsm_scanner --args=hackrf`
