### ISSUE TITLE
Error " sudo ./pybombs config "

### ISSUE THREAD

**Issue by lamld** [ptrkrysik/gr-gsm#92]
I can't config pybombs. I don't know why. Can you help me, please !

lamledinh@lamledinh-PC:~/pybombs$ sudo ./pybombs config
[sudo] password for lamledinh: 
Initializing config file...
Username for GIT access
gituser [root]:
Directory of git cache repository
gitcache []:
Options to always pass to git clones (--depth=1 or --single-branch will speed up clones)
gitoptions []:
Install Prefix
Traceback (most recent call last):
File "./pybombs", line 25, in 
from mod_pybombs import verbosity as v
File "/home/lamledinh/pybombs/mod_pybombs/init.py", line 22, in 
from globals import *;
File "/home/lamledinh/pybombs/mod_pybombs/globals.py", line 48, in 
config_init(config);
File "/home/lamledinh/pybombs/mod_pybombs/cfg.py", line 70, in config_init
if os.path.basename(pwd)=="pybombs":
File "/usr/lib/python2.7/posixpath.py", line 121, in basename
i = p.rfind('/') + 1
AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by ptrkrysik** [comment]
This is error in pybombs. I've filled bugreport.
